# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'board_selection.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(611, 443)
        Form.setStyleSheet("#Form {\n"
"    background: #2D2C3F;\n"
"}")
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 571, 524))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.vlayout_main = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.vlayout_main.setContentsMargins(2, 2, 2, 2)
        self.vlayout_main.setObjectName("vlayout_main")
        self.button_create_board = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.button_create_board.setObjectName("button_create_board")
        self.vlayout_main.addWidget(self.button_create_board)
        self.scroll_area = QtWidgets.QScrollArea(self.verticalLayoutWidget)
        self.scroll_area.setStyleSheet("#scroll_area_items {\n"
"    background-color: transperent;\n"
"}")
        self.scroll_area.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scroll_area.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scroll_area.setWidgetResizable(True)
        self.scroll_area.setObjectName("scroll_area")
        self.scroll_area_widget_container = QtWidgets.QWidget()
        self.scroll_area_widget_container.setGeometry(QtCore.QRect(0, 0, 567, 491))
        self.scroll_area_widget_container.setStyleSheet("#scroll_area_widget_container {\n"
"    background: #2D2C3F;\n"
"}")
        self.scroll_area_widget_container.setObjectName("scroll_area_widget_container")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.scroll_area_widget_container)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(20, 20, 521, 361))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.vlayout_items = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.vlayout_items.setContentsMargins(0, 0, 0, 0)
        self.vlayout_items.setObjectName("vlayout_items")
        self.scroll_area.setWidget(self.scroll_area_widget_container)
        self.vlayout_main.addWidget(self.scroll_area)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Yello"))
        self.button_create_board.setText(_translate("Form", "Добавить доску"))
