# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'board_edit.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(902, 704)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(0, 180))
        Form.setStyleSheet("#Form {\n"
"    background: #2D2C3F;\n"
"}")
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 481, 451))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.vlayout_main = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.vlayout_main.setContentsMargins(0, 0, 0, 0)
        self.vlayout_main.setObjectName("vlayout_main")
        self.widget_navbar = QtWidgets.QWidget(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_navbar.sizePolicy().hasHeightForWidth())
        self.widget_navbar.setSizePolicy(sizePolicy)
        self.widget_navbar.setMinimumSize(QtCore.QSize(0, 60))
        self.widget_navbar.setStyleSheet("#widget_navbar {\n"
"    background: #241E35;\n"
"}")
        self.widget_navbar.setObjectName("widget_navbar")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.widget_navbar)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 461, 61))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.hlayout_navbar = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.hlayout_navbar.setContentsMargins(10, 10, 2, 2)
        self.hlayout_navbar.setSpacing(10)
        self.hlayout_navbar.setObjectName("hlayout_navbar")
        self.vlayout_main.addWidget(self.widget_navbar)
        self.scroll_area_window = QtWidgets.QScrollArea(self.verticalLayoutWidget)
        self.scroll_area_window.setStyleSheet("#scroll_area_window {\n"
"    background-color: transperent;\n"
"}")
        self.scroll_area_window.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scroll_area_window.setWidgetResizable(True)
        self.scroll_area_window.setObjectName("scroll_area_window")
        self.scroll_area_widget_window = QtWidgets.QWidget()
        self.scroll_area_widget_window.setGeometry(QtCore.QRect(0, 0, 479, 383))
        self.scroll_area_widget_window.setStyleSheet("#scroll_area_widget_window {\n"
"    background: #2D2C3F;\n"
"}")
        self.scroll_area_widget_window.setObjectName("scroll_area_widget_window")
        self.widget = QtWidgets.QWidget(self.scroll_area_widget_window)
        self.widget.setGeometry(QtCore.QRect(-50, 10, 479, 383))
        self.widget.setObjectName("widget")
        self.hlayout_groups = QtWidgets.QHBoxLayout(self.widget)
        self.hlayout_groups.setContentsMargins(0, 0, 0, 0)
        self.hlayout_groups.setSpacing(3)
        self.hlayout_groups.setObjectName("hlayout_groups")
        self.gridLayout_add_button_container = QtWidgets.QGridLayout()
        self.gridLayout_add_button_container.setObjectName("gridLayout_add_button_container")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_add_button_container.addItem(spacerItem, 2, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_add_button_container.addItem(spacerItem1, 0, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_add_button_container.addItem(spacerItem2, 1, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_add_button_container.addItem(spacerItem3, 1, 0, 1, 1)
        self.button_add_group = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_add_group.sizePolicy().hasHeightForWidth())
        self.button_add_group.setSizePolicy(sizePolicy)
        self.button_add_group.setMinimumSize(QtCore.QSize(165, 40))
        self.button_add_group.setMaximumSize(QtCore.QSize(165, 55))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        self.button_add_group.setFont(font)
        self.button_add_group.setStyleSheet("#button_add_group {\n"
"    border-color: #0DF5E3;\n"
"    border-style: outset;\n"
"    border-radius: 0.625em;\n"
"    \n"
"    padding-left: 0.625em;\n"
"    padding-right: 0.625em;\n"
"    padding-top: 0.3em;\n"
"    padding-bottom:  0.3em;\n"
"\n"
"    color: #FFFFFF;\n"
"    background-color: #514265;\n"
"}\n"
"\n"
"#button_add_group::hover {\n"
"    background-color: #5A4970;\n"
"    border-color: #5A4970;\n"
"}\n"
"\n"
"#button_add_group:pressed {\n"
"    background-color: #63507B;\n"
"    border-color: #33D2C6;\n"
"    outline: none;\n"
"}")
        self.button_add_group.setObjectName("button_add_group")
        self.gridLayout_add_button_container.addWidget(self.button_add_group, 1, 1, 1, 1)
        self.hlayout_groups.addLayout(self.gridLayout_add_button_container)
        self.scroll_area_window.setWidget(self.scroll_area_widget_window)
        self.vlayout_main.addWidget(self.scroll_area_window)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Yello"))
        self.button_add_group.setText(_translate("Form", "Добавить группу"))
